{"result":{"history_size":1,"folders":["hw1"],"nr":56,"data":{"embed_links":[]},"created":"2024-10-12T17:03:54Z","bucket_order":3,"no_answer_followup":0,"change_log":[{"anon":"stud","data":"m26eom4x4qo4lt","v":"all","type":"create","when":"2024-10-12T17:03:54Z","uid_a":"a_0"},{"anon":"no","uid":"ku2mpnf09v965r","data":"m26etn4lddl6qa","to":"m26eom4fpng4lr","type":"i_answer","when":"2024-10-12T17:07:49Z"},{"anon":"stud","to":"m26eom4fpng4lr","type":"followup","when":"2024-10-12T17:17:35Z","cid":"m26f6731xrp6b9","uid_a":"a_0"},{"anon":"no","uid":"m1fj3gtoqv33v0","data":"m26f9gqz3xw5w5","to":"m26eom4fpng4lr","type":"s_answer","when":"2024-10-12T17:20:07Z"},{"anon":"no","uid":"m1fj3gtoqv33v0","data":"m26fgz0hlfr7fj","type":"s_answer_update","when":"2024-10-12T17:25:57Z"},{"anon":"no","uid":"m1fj3gtoqv33v0","data":"m26fhu696c917m","type":"s_answer_update","when":"2024-10-12T17:26:38Z"},{"anon":"stud","to":"m26eom4fpng4lr","type":"feedback","when":"2024-10-12T17:34:28Z","cid":"m26frwsvr3fhs","uid_a":"a_0"},{"anon":"stud","to":"m26eom4fpng4lr","type":"feedback","when":"2024-10-15T18:00:41Z","cid":"m2ar16n2acs41p","uid_a":"a_1"},{"anon":"stud","to":"m26eom4fpng4lr","type":"feedback","when":"2024-10-15T18:08:48Z","cid":"m2arbmpln1n5qx","uid_a":"a_1"},{"anon":"no","uid":"m1cpwqub88a6ef","to":"m26eom4fpng4lr","type":"followup","when":"2024-10-19T01:51:20Z","cid":"m2fi5zoo2cd5ev"}],"bucket_name":"Today","history":[{"anon":"stud","uid_a":"a_0","subject":"Gradescope tests failing from &#39;np&#39; not defined","created":"2024-10-12T17:03:54Z","content":"<p>I didn&#39;t rename my numpy import as np, so I&#39;m not sure why this is happening. Is this a problem on my side, or Gradescope&#39;s?</p>\n<p></p>\n<p><img src=\"/redirect/s3?bucket=uploads&amp;prefix=paste%2Fm1cpwpc5q8r6ap%2Fd3a3a51d683a86f62c100faec299b4e7fa7953210bd49f0df4f25a23db628465%2Fimage.png\" alt=\"image.png\" /></p>"}],"type":"question","tags":["hw1","student"],"tag_good":[],"unique_views":331,"children":[{"history_size":1,"folders":[],"data":{"embed_links":[]},"created":"2024-10-12T17:07:49Z","bucket_order":3,"tag_endorse":[],"bucket_name":"Today","history":[{"anon":"no","uid":"ku2mpnf09v965r","subject":"","created":"2024-10-12T17:07:49Z","content":"Could you check your code and see if there are any np in it?"}],"type":"i_answer","tag_endorse_arr":[],"children":[],"id":"m26etn4eget6q8","config":{},"is_tag_endorse":false},{"anon":"stud","folders":[],"data":{"embed_links":null},"no_upvotes":0,"subject":"No instances of &#39;np&#39; anywhere, but I&#39;m theorizing that it&#39;s probably my answer values are of np.float instead of python primitives. Will edit and mark as solved if this is the case.","created":"2024-10-12T17:17:35Z","bucket_order":5,"bucket_name":"This week","type":"followup","tag_good":[],"uid_a":"a_0","children":[{"anon":"stud","folders":[],"data":{"embed_links":null},"subject":"This was it; thank you Bingnan for the in-depth explanation as well.","created":"2024-10-12T17:34:28Z","bucket_order":6,"bucket_name":"Last week","type":"feedback","tag_good":[],"uid_a":"a_0","children":[],"tag_good_arr":[],"id":"m26frwsvr3fhs","updated":"2024-10-12T17:34:28Z","config":{"editor":"rte"}},{"anon":"stud","folders":[],"data":{"embed_links":null},"subject":"hey, how did you resolve this? i tried to convert the answers from np to float(), but it still throws an error","created":"2024-10-15T18:00:41Z","bucket_order":4,"bucket_name":"Yesterday","type":"feedback","tag_good":[{"role":"student","name":"Xiaoran Wan","endorser":{},"admin":false,"photo":null,"id":"lzg4y7q5ioy7ct","photo_url":null,"published":true,"us":false,"facebook_id":null}],"uid_a":"a_1","children":[],"tag_good_arr":["lzg4y7q5ioy7ct"],"id":"m2ar16n2acs41p","d-bucket":"Yesterday","updated":"2024-10-18T07:19:52Z","config":{"editor":"rte"}},{"anon":"stud","folders":[],"data":{"embed_links":null},"subject":"i have just tried for first one as of now, but even on the first one it is throwing the &#39;np not found&#39; error","created":"2024-10-15T18:08:48Z","bucket_order":4,"bucket_name":"Yesterday","type":"feedback","tag_good":[{"role":"student","name":"Xiaoran Wan","endorser":{},"admin":false,"photo":null,"id":"lzg4y7q5ioy7ct","photo_url":null,"published":true,"us":false,"facebook_id":null}],"uid_a":"a_1","children":[],"tag_good_arr":["lzg4y7q5ioy7ct"],"id":"m2arbmpln1n5qx","d-bucket":"Yesterday","updated":"2024-10-18T07:19:53Z","config":{"editor":"rte"}}],"tag_good_arr":[],"no_answer":0,"id":"m26f6731xrp6b9","updated":"2024-10-15T18:08:48Z","config":{"editor":"rte"}},{"history_size":3,"folders":[],"data":{"embed_links":[]},"created":"2024-10-12T17:20:07Z","bucket_order":3,"tag_endorse":[{"role":"student","name":"Stone Yang","endorser":{},"admin":false,"photo":null,"id":"m1cpwpc5q8r6ap","photo_url":null,"us":false,"facebook_id":null}],"bucket_name":"Today","history":[{"anon":"no","uid":"m1fj3gtoqv33v0","subject":"","created":"2024-10-12T17:26:38Z","content":"<p>Try to convert your answer by using <a href=\"https://numpy.org/doc/2.0/reference/generated/numpy.ndarray.item.html\" target=\"_blank\" rel=\"noopener noreferrer\">numpy.ndarray.item()</a>.</p>\n<p></p>\n<p>Actually, even if you didn&#39;t rename <kbd>numpy</kbd> as <kbd>np</kbd>, the data type in <kbd>numpy</kbd> is defined as <kbd>np.xxx</kbd>. You can try the following code:<kbd><br /></kbd></p>\n<p></p>\n<pre>\nimport numpy\n\na = numpy.float32(1)\nb = {&#34;Q1&#34;: a}\nwith open(&#34;test.txt&#34;, &#34;w&#34;) as f:\n    f.write(str(b))</pre>\n<p>and you will see the output file like:</p>\n<pre>\n{&#39;Q1&#39;: np.float32(1.0)}</pre>\n<p></p>\n<p>I guess the autograder just read in the .txt file and use <kbd>eval</kbd> to convert the string into a dict and compare with the standard answer. Then the problem happens when the autograder didn&#39;t import <kbd>numpy</kbd> as <kbd>np</kbd> and <kbd>eval</kbd> can&#39;t run correctly.</p>\n<p></p>\n<p>To verify, try to add the following code:</p>\n<pre>\nwith open(&#34;test.txt&#34;, &#34;r&#34;) as f:\n    c = eval(f.read())\n    print(c[&#34;Q1&#34;])</pre>\n<p>and you will get a run time error like:</p>\n<p></p>\n<pre>\nTraceback (most recent call last):\n  File &#34;xxxx.py&#34;, line 9, in &lt;module&gt;\n    c = eval(f.read())\n        ^^^^^^^^^^^^^^\n  File &#34;&lt;string&gt;&#34;, line 1, in &lt;module&gt;\nNameError: name &#39;np&#39; is not defined</pre>"},{"anon":"no","uid":"m1fj3gtoqv33v0","subject":"","created":"2024-10-12T17:25:57Z","content":"<p>Try to convert your answer by using <a href=\"https://numpy.org/doc/2.0/reference/generated/numpy.ndarray.item.html\" target=\"_blank\" rel=\"noopener noreferrer\">numpy.ndarray.item()</a>.</p>\n<p></p>\n<p>Actually, even if you didn&#39;t rename <kbd>numpy</kbd> as <kbd>np</kbd>, the data type in <kbd>numpy</kbd> is defined as <kbd>np.xxx</kbd>. You can try the following code:<kbd><br /></kbd></p>\n<p></p>\n<pre>\nimport numpy\n\na = numpy.float32(1)\nb = {&#34;Q1&#34;: a}\nwith open(&#34;test.txt&#34;, &#34;w&#34;) as f:\n    f.write(str(b))</pre>\n<p>and you will see the output file like:</p>\n<pre>\n{&#39;Q1&#39;: np.float32(1.0)}</pre>\n<p></p>\n<p>I guess the autograder just read in the .txt file and use <kbd>eval</kbd> to convert the string into a dict and compare with the standard answer. Then the problem happens when the autograder didn&#39;t import <kbd>numpy</kbd> and <kbd>eval</kbd> can&#39;t run correctly.</p>\n<p></p>\n<p>To verify, try to add the following code:</p>\n<pre>\nwith open(&#34;test.txt&#34;, &#34;r&#34;) as f:\n    c = eval(f.read())\n    print(c[&#34;Q1&#34;])</pre>\n<p>and you will get a run time error like:</p>\n<p></p>\n<pre>\nTraceback (most recent call last):\n  File &#34;xxxx.py&#34;, line 9, in &lt;module&gt;\n    c = eval(f.read())\n        ^^^^^^^^^^^^^^\n  File &#34;&lt;string&gt;&#34;, line 1, in &lt;module&gt;\nNameError: name &#39;np&#39; is not defined</pre>"},{"anon":"no","uid":"m1fj3gtoqv33v0","subject":"","created":"2024-10-12T17:20:07Z","content":"<p>Try to convert your answer by using <a href=\"https://numpy.org/doc/2.0/reference/generated/numpy.ndarray.item.html\" target=\"_blank\" rel=\"noopener noreferrer\">numpy.ndarray.item()</a>.</p>\n<p></p>\n<p>Actually, even if you didn&#39;t rename <kbd>numpy</kbd> as <kbd>np</kbd>, the data type in <kbd>numpy</kbd> is defined as <kbd>np.xxx</kbd>. You can try the following code:<kbd><br /></kbd></p>\n<p></p>\n<pre>\nimport numpy\n\na = numpy.float32(1)\nb = {&#34;Q1&#34;: a}\nwith open(&#34;test.txt&#34;, &#34;w&#34;) as f:\n    f.write(str(b))</pre>\n<p>and you will see the output file like:</p>\n<pre>\n{&#39;Q1&#39;: np.float32(1.0)}</pre>\n<p></p>\n<p>I guess the autograder just read in the .txt file and use <kbd>eval</kbd> to convert the string into a dict and compare with the standard answer. Then the problem happens when the autograder didn&#39;t import <kbd>numpy</kbd> and <kbd>eval</kbd> can&#39;t run correctly.</p>"}],"type":"s_answer","tag_endorse_arr":["m1cpwpc5q8r6ap"],"children":[],"id":"m26f9gqv1ma5w4","config":{"editor":"rte"},"is_tag_endorse":false},{"anon":"no","folders":[],"data":{"embed_links":null},"no_upvotes":0,"subject":"<p>Another easy solution for future reference - add this line of code</p>\n<p></p>\n<p>numpy.set_printoptions(legacy=&#39;1.25&#39;)</p>","created":"2024-10-19T01:51:20Z","bucket_order":3,"bucket_name":"Today","type":"followup","tag_good":[],"uid":"m1cpwqub88a6ef","children":[],"tag_good_arr":[],"no_answer":0,"id":"m2fi5zoo2cd5ev","updated":"2024-10-19T01:51:22Z","config":{"editor":"rte"}}],"tag_good_arr":[],"no_answer":0,"id":"m26eom4fpng4lr","config":{"editor":"rte","has_emails_sent":1},"status":"active","drafts":{},"request_instructor":0,"request_instructor_me":false,"bookmarked":7,"num_favorites":3,"my_favorite":false,"is_bookmarked":false,"is_tag_good":false,"q_edits":[],"i_edits":[],"s_edits":[],"t":1731989101799,"default_anonymity":"no"},"error":null,"aid":"m3nxlbyyu381do"}