{"result":{"history_size":1,"folders":["hw2","logistics"],"nr":139,"data":{"embed_links":[]},"created":"2024-10-28T01:46:38Z","bucket_order":3,"no_answer_followup":0,"change_log":[{"anon":"stud","data":"m2scymtar1wvs","v":"all","type":"create","when":"2024-10-28T01:46:38Z","uid_a":"a_0"},{"anon":"no","uid":"kfo0vtto1k321a","data":"m2sg7xhkb9d5e5","to":"m2scymt0vn0vr","type":"i_answer","when":"2024-10-28T03:17:51Z"}],"bucket_name":"Today","history":[{"anon":"stud","uid_a":"a_0","subject":"HW2 Submission","created":"2024-10-28T01:46:38Z","content":"<p>Hi,</p>\n<p></p>\n<p>I keep getting an error that says my submitted file looks like an .ipynb, and all the test cases fail. I don&#39;t know why this occurs, since I submit a .py file each time. Please let me know what to do - I want to make sure my outputs are correct but can&#39;t do so.</p>"}],"type":"question","tags":["hw2","logistics","student"],"tag_good":[],"unique_views":216,"children":[{"history_size":1,"folders":[],"data":{"embed_links":[]},"created":"2024-10-28T03:17:51Z","bucket_order":3,"tag_endorse":[],"bucket_name":"Today","history":[{"anon":"no","uid":"kfo0vtto1k321a","subject":"","created":"2024-10-28T03:17:51Z","content":"<md>You need to export the .ipynb file to a real .py file, instead of simply renaming it.</md>"}],"type":"i_answer","tag_endorse_arr":[],"children":[],"id":"m2sg7xhdinn5e4","config":{"editor":"md"},"is_tag_endorse":false}],"tag_good_arr":[],"no_answer":0,"id":"m2scymt0vn0vr","config":{"editor":"rte","has_emails_sent":1},"status":"active","drafts":{},"request_instructor":0,"request_instructor_me":false,"bookmarked":3,"num_favorites":0,"my_favorite":false,"is_bookmarked":false,"is_tag_good":false,"q_edits":[],"i_edits":[],"s_edits":[],"t":1731986400773,"default_anonymity":"no"},"error":null,"aid":"m3nvzfugy2g4vt"}